global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "api-service:8000"
  
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
